# Site settings
title: DEFINITELY MAYBE
email: tekkahs@gmail.com
description: "Mr.Raindrop's Tech Memo."
baseurl: ""
encoding: "utf-8"
url: "http://mrraindrop.com"
github_username:  Mr.Raindrop

# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:year/:month/:day/:title