# Site settings
title: DEFINITELY P&H
email: tekkahs@gmail.com
description: "A BUG NEVER FIXED, A EXCEPTION NEVER THROWN."
baseurl: ""
encoding: "utf-8"
url: "http://mrraindrop.com"
github_username:  __MrRaindrop__

# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:year/:month/:day/:title