# Site settings
title: DEFINITELY MAYBE
email: tekkahs@gmail.com
description: "Mr.Raindrop's Tech Memo."
baseurl: "http://mrraindrop.com"
encoding: "utf-8"
url: "http://mrraindrop.com"
github_username: MrRaindrop

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["node_modules"]