# Site settings
title: DEFINITELY MAYBE
email: tekkahs@gmail.com
description: "Mr.Raindrop's Tech Memo."
baseurl: ""
encoding: "utf-8"
url: "http://mrraindrop.com"
github_username: MrRaindrop
weibo_username: rurouni

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
permalink: /:year/:month/:day/:title
paginate: 8
exclude: ["node_modules"]